In [9]:
import numpy as np
import pandas as pd

In [4]:
arr = np.array([1,2,3,4,5,6,7])
arr

array([1, 2, 3, 4, 5, 6, 7])

In [5]:
# check the numpy version

print(np.__version__)


1.24.3


In [6]:
type(arr)

numpy.ndarray

In [2]:
a = np.array(41)
b = np.array([22, 33, 44, 66, 78, 100])
c = np.array([[1,2,3], [5,6,7]])
d = np.array([[[1,2,3], [5,6,7]], [[1,2,3], [4,5,6]]]) 

e = np.array(10, ndmin=5)


print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim) 

print(e.ndim)
print(e)

0
1
2
3
5
[[[[[10]]]]]


In [18]:
print(c[1, -1])

7


In [12]:
print(b[2])

44


In [13]:
print(c[1, 2])

7


In [15]:
print(d[0, 1, 1])

6


In [16]:
print(d[0, 0, 2])

3


In [42]:
arr = np.array([22, 33, 44, 66, 78, 100, 7, 8])

print(arr[:4])

[22 33 44 66]


In [35]:
print(arr[4:])

[ 78 100   7   8]


In [36]:
print(arr[1 : 4])

[33 44 66]


In [37]:
print(arr[-2:])

[7 8]


In [38]:
print(arr[1 : -2])

[ 33  44  66  78 100]


In [39]:
print(arr[-3:-1])

[100   7]


In [41]:
# print step two
print(arr[::2])

[22 44 78  7]


In [43]:
arr2 = np.array([[1,2,3], [5,6,7]])

print(arr2[1, 1:2])

[6]


In [57]:
arr3 = np.array([[[1,2,3], [5,6,7]], [[1,2,3], [4,5,6]]])

            

print(arr3[1, 1, 1:])

[5 6]


In [4]:
print(b.dtype)

int32


In [5]:
fruits = np.array(['apple', 'banana', 'cherry'])
print(fruits)

['apple' 'banana' 'cherry']


In [7]:
print(fruits.dtype)

<U6


In [8]:
numbers = np.array([1,2,3,4,5], dtype="S")

print(numbers.dtype)


|S1


In [3]:
# float to integer

arr = np.array([1.1, 1.3, 1.4])

# new_arr = arr.astype('i')
new_arr = arr.astype(int)


print(arr.dtype)
print(new_arr.dtype)



float64
int32


In [2]:
num = np.array([1, 0, 0, 2, 3])

new_arr = num.astype(bool)

print(num)
print(new_arr)


[1 0 0 2 3]
[ True False False  True  True]


In [2]:
arr = np.array([1, 2, 3, 4, 5])

# dont change orginal array
x = arr.copy()

x[0] = 43
x[2] = 400

print(arr)
print(x)

[1 2 3 4 5]
[ 43   2 400   4   5]


In [3]:
# it change the orginal array
y = arr.view()
y[0] = 30

print(arr)
print(y)



[30  2  3  4  5]
[30  2  3  4  5]


In [36]:
arr = np.array([[1,2,3,4,5], [1,2,3,4,5]])

# print(arr.ndim)
# print(arr.shape)

for x in arr:
    print("==")
    print(x)
    for y in x:
        print(y)



==
[1 2 3 4 5]
1
2
3
4
5
==
[1 2 3 4 5]
1
2
3
4
5


In [19]:
arr2 = np.array([1,2,3,4,5] , ndmin=3)

print(arr2.ndim)
print(arr2.shape)


3
(1, 1, 5)


In [29]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])


# new_arr = arr.reshape(4, 3)
new_arr = arr.reshape(2, 3, 2)

print(arr.reshape(2, 3, 2))
print(new_arr.shape)

print(arr.reshape(-1))



[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [39]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    for y in x:
        for z in y:
            print(z)


1
2
3
4
5
6
7
8
9
10
11
12


In [43]:
# this is other way to iterate 3-D array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

new_arr = arr.reshape(-1)

for x in new_arr:
    print(x, end=" ")
print()
print(new_arr)


1 2 3 4 5 6 7 8 9 10 11 12 
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [44]:

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in np.nditer(arr):
    print(x)


1
2
3
4
5
6
7
8
9
10
11
12


In [47]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for index, x in np.ndenumerate(arr):
    print(index, x)


(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 10
(1, 1, 1) 11
(1, 1, 2) 12


In [52]:

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [56]:

arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])


# arr = np.concatenate((arr1, arr2))
arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [58]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])


arr = np.stack((arr1, arr2), axis=1)
print(arr)


[[1 4]
 [2 5]
 [3 6]]


In [3]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

# row
arr = np.hstack((arr1, arr2))
print(arr)


[1 2 3 4 5 6]


In [4]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

# column
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [62]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])


arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18], [19, 20, 21]])

new_arr = np.array_split(arr, 3)
# new_arr = np.array_split(arr, 3, axis=1)

print(new_arr[0])
print("==")
print(new_arr[1])
print("==")
print(new_arr[2])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
==
[[10 11 12]
 [13 14 15]]
==
[[16 17 18]
 [19 20 21]]


In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

new_arr = np.hsplit(arr, 3)

print(new_arr[0])
print("==")
print(new_arr[1])
print("==")
print(new_arr[2])

[[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]]
==
[[ 2]
 [ 5]
 [ 8]
 [11]
 [14]
 [17]]
==
[[ 3]
 [ 6]
 [ 9]
 [12]
 [15]
 [18]]


In [11]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#return the index
x = np.where(arr == 4)

print(x)

(array([3], dtype=int64),)


In [12]:

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5], dtype=int64),)


In [13]:
x = np.where(arr % 2 == 1)

print(x)



(array([0, 2, 4], dtype=int64),)


In [14]:
# its working like binary search
x = np.searchsorted(arr, 4)
print(x)

3


In [21]:
arr = np.array([6, 7, 8, 9])

xx = np.searchsorted(arr, 7, side='right')

print(xx)

2


In [22]:
print(np.sort(arr))

[6 7 8 9]


In [24]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))


['apple' 'banana' 'cherry']


In [25]:
arr = np.array([True, False, True, False])

print(np.sort(arr))


[False False  True  True]


In [27]:
arr1 = np.array([[-1,22,3],[44,5,9]])

print(np.sort(arr1))

[[-1  3 22]
 [ 5  9 44]]


In [28]:

arr = np.array([41, 45, 59, 42])

# ist count olny true array 
x = [True, False, False, True]

new_arr = arr[x]

print(new_arr)



[41 42]


In [30]:
arr = np.array([41, 42, 43, 44])

filter_arr = []

for x in arr:
    if x > 42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
        

xx = arr[filter_arr]

print(xx)



[43 44]


In [35]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

xx = arr[filter_arr]
print(xx)


[2 4 6]


In [50]:
from numpy import random

x = random.randint(100)

print(x)

59


In [57]:
x = random.rand()

print(x)

0.7285274409545665


In [63]:
x = random.randint(100, size=(10, 5))

print(x)

[[ 1 73 96  8  1]
 [19 95 90 94 86]
 [88 88 34 77 81]
 [75 75 48 87  9]
 [85 18 11 63 45]
 [98 75 13 12 21]
 [78 40 95 12 30]
 [50 41 78 76  5]
 [36 36 97 55 43]
 [ 7 43 70  2 52]]


In [73]:
x = random.rand(3, 5)
print(x)

[[0.86469737 0.0641941  0.85281605 0.92562413 0.86007013]
 [0.74957223 0.99971197 0.10828553 0.65505159 0.5988651 ]
 [0.32588389 0.64262905 0.2186156  0.90203211 0.82968501]]


In [74]:
x = random.choice([5, 3, 7, 1, 8], size=(3, 4))
print(x)

[[3 3 1 3]
 [8 3 5 8]
 [8 1 5 8]]


In [75]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])

print(arr
[1:4]
)

[15 20 25]


In [77]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])

print(arr[1:4:2])



[15 25]


In [78]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])

print(arr
[::2]
)

[10 20 30 40]


In [7]:
arr = np.array([-1, 0, 1])
newarr = arr.astype(bool)
print(newarr)

[ True False  True]


## Aggregation


In [16]:

massive_array = np.random.random(10000)
massive_array.size

10000

In [21]:
massive_array[:10]

array([0.13337182, 0.20972348, 0.93725942, 0.85999589, 0.89623315,
       0.67160389, 0.74210983, 0.26983853, 0.47724614, 0.19344925])

In [22]:
massive_array

array([0.13337182, 0.20972348, 0.93725942, ..., 0.2652115 , 0.03884087,
       0.06079596])

In [23]:
sum(massive_array)

5015.788687494897

In [24]:
np.sum(massive_array)

5015.788687494893

In [26]:
%timeit sum(massive_array) # python sum
%timeit np.sum(massive_array) # numpy np.sum

679 µs ± 9.72 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
7.01 µs ± 91.6 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [3]:
a1 = np.random.random(100)

In [54]:
a1

array([0.04616985, 0.3507477 , 0.51149053, 0.91141371, 0.54532319,
       0.31254611, 0.7096165 , 0.00707677, 0.96308254, 0.28614923,
       0.71050713, 0.97819627, 0.91362898, 0.95501271, 0.47100394,
       0.63615724, 0.95754176, 0.78701313, 0.26938154, 0.5261564 ,
       0.97824741, 0.41093618, 0.84130926, 0.22727702, 0.6140045 ,
       0.30107493, 0.65243798, 0.37294983, 0.29513292, 0.30278287,
       0.84962286, 0.33862345, 0.01245622, 0.29374254, 0.43140719,
       0.51953277, 0.52850386, 0.70816106, 0.83054869, 0.94806067,
       0.02912047, 0.32706303, 0.38177736, 0.67416762, 0.68446863,
       0.51650828, 0.39471874, 0.64866132, 0.99497966, 0.79122087,
       0.40274308, 0.0682294 , 0.86068881, 0.82003703, 0.80883515,
       0.13923572, 0.92703961, 0.78860956, 0.50778153, 0.63782569,
       0.81001007, 0.73201515, 0.27249831, 0.73171256, 0.32627025,
       0.84390943, 0.48979685, 0.78589085, 0.10054226, 0.09521326,
       0.4422845 , 0.50714486, 0.26212565, 0.45970264, 0.51843

In [55]:
a1

array([0.04616985, 0.3507477 , 0.51149053, 0.91141371, 0.54532319,
       0.31254611, 0.7096165 , 0.00707677, 0.96308254, 0.28614923,
       0.71050713, 0.97819627, 0.91362898, 0.95501271, 0.47100394,
       0.63615724, 0.95754176, 0.78701313, 0.26938154, 0.5261564 ,
       0.97824741, 0.41093618, 0.84130926, 0.22727702, 0.6140045 ,
       0.30107493, 0.65243798, 0.37294983, 0.29513292, 0.30278287,
       0.84962286, 0.33862345, 0.01245622, 0.29374254, 0.43140719,
       0.51953277, 0.52850386, 0.70816106, 0.83054869, 0.94806067,
       0.02912047, 0.32706303, 0.38177736, 0.67416762, 0.68446863,
       0.51650828, 0.39471874, 0.64866132, 0.99497966, 0.79122087,
       0.40274308, 0.0682294 , 0.86068881, 0.82003703, 0.80883515,
       0.13923572, 0.92703961, 0.78860956, 0.50778153, 0.63782569,
       0.81001007, 0.73201515, 0.27249831, 0.73171256, 0.32627025,
       0.84390943, 0.48979685, 0.78589085, 0.10054226, 0.09521326,
       0.4422845 , 0.50714486, 0.26212565, 0.45970264, 0.51843

In [58]:
# standard Deviation
np.std(a1)

0.2924165196929205

In [7]:
# Variance = measure of the average degree to which each number is difference to the mean
# Higher variance = wider range of numbers
# lower variance = lower range of numbers
np.var(a1)

0.07602539844566614

In [8]:

# standard Deviation = Squireroot of variance

np.sqrt(np.var(a1))



0.2757270361166386

In [5]:
# Demo of std and var

high_var_array = np.array([1, 100, 200, 300, 4000, 5000])
low_var_array = np.array([2, 4, 6, 8, 10])


In [6]:
np.var(high_var_array), np.var(low_var_array)

(4296133.472222221, 8.0)

In [9]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)


In [11]:
newarr.shape

(2, 3, 2)

In [12]:
newarr.ndim

3

In [36]:
a1 = np.array([[1,2,3], [4,5,6]])

In [14]:
a1.shape

(2, 3)

In [15]:
a2 = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[10,11,12], [13,14,15], [16,17,17]]])

In [18]:
a2.shape

(2, 3, 3)

In [19]:
a1 * a2

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [30]:
a1 = a1.reshape(2, 3, 1)

In [34]:
a1

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [31]:
a1.shape

(2, 3, 1)

In [37]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
a1 * a2

array([[[  1,   2,   3],
        [  8,  10,  12],
        [ 21,  24,  27]],

       [[ 40,  44,  48],
        [ 65,  70,  75],
        [ 96, 102, 102]]])

In [44]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
a1.shape

(2, 3)

In [46]:
# Transpose
a1.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## Dot product 

In [48]:
np.dot(3, 5)

15

In [59]:
np.random.seed(0)
mat1 = np.random.randint(10, size=(5, 3))
mat2 = np.random.randint(10, size=(5, 3))

In [66]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [76]:
mat1, mat2

(array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6],
        [8, 8, 1]]),
 array([[6, 7, 7],
        [8, 1, 5],
        [9, 8, 9],
        [4, 3, 0],
        [3, 5, 0]]))

In [80]:
mat2.T

array([[6, 5, 3],
       [7, 9, 0],
       [7, 8, 3],
       [8, 9, 5],
       [1, 4, 0]])

In [81]:
mat1.shape, mat2.shape

((5, 3), (3, 5))

In [82]:
# Element wise multiplication 
mat1 * mat2

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

In [83]:
# dot products

np.dot(mat1, mat2)


array([[ 39,  35,  44,  55,   5],
       [ 80,  84, 104, 132,  31],
       [ 49,  66,  67,  79,  23],
       [ 77,  91, 102, 125,  32],
       [ 91, 128, 123, 141,  40]])

## Dot product example (Nut butter sale)

In [70]:
np.random.seed(0)

sales_amount = np.random.randint(20, size=(5, 3))

sales_amount


array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [11]:
weekly_sales = pd.DataFrame(sales_amount,
                           index=["Mon", "Sat", "Tue", "Wed", "Thurs"],
                           columns=["Almond butter", "Peanut Butter", "Cashew Butter"])

weekly_sales


Almond butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Sat                3              3              7
Tue                9             19             18
Wed                4              6             12
Thurs              1              6              7

In [24]:
# create butter price dataframe

butter_price = pd.DataFrame(price.reshape(1, 3), 
                           index=["Price"],
                           columns=["Almond butter", "Peanut Butter", "Cashew Butter"])

butter_price

Almond butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [91]:
# total_sales = sales_amount.dot(price.T)
daily_sales = butter_price.dot(weekly_sales.T)

In [96]:
daily_sales

Mon  Sat  Tue  Wed  Thurs
Price  240  138  458  232    142

In [101]:
daily_sales.shape

(1, 5)

In [99]:
weekly_sales.shape

(5, 4)

In [94]:
#create daily sale
weekly_sales['Total'] = daily_sales.T

In [95]:
weekly_sales

Almond butter  Peanut Butter  Cashew Butter  Total
Mon               12             15              0    240
Sat                3              3              7    138
Tue                9             19             18    458
Wed                4              6             12    232
Thurs              1              6              7    142

## sorting

In [103]:
random_array = np.random.randint(20, size=(3, 5))
random_array

array([[14, 17,  5, 13,  8],
       [ 9, 19, 16, 19,  5],
       [15, 15,  0, 18,  3]])

In [104]:
np.sort(random_array)

array([[ 5,  8, 13, 14, 17],
       [ 5,  9, 16, 19, 19],
       [ 0,  3, 15, 15, 18]])

In [108]:
# show element wise index
np.argsort(random_array)

array([[2, 4, 3, 0, 1],
       [4, 0, 2, 1, 3],
       [2, 4, 0, 1, 3]], dtype=int64)

In [109]:
random_array

array([[14, 17,  5, 13,  8],
       [ 9, 19, 16, 19,  5],
       [15, 15,  0, 18,  3]])

In [107]:
# axis=0 means column
np.argmax(random_array, axis=0)

array([2, 1, 1, 1, 0], dtype=int64)

In [110]:
# axis=1 means row
np.argmax(random_array, axis=1)

array([1, 1, 3], dtype=int64)

## Practical example numpy in action

In [119]:
from matplotlib.image import imread

In [121]:
img_arr = imread('images/cat.png')
print(type(img))

<class 'numpy.ndarray'>


In [122]:
img_arr

array([[[0.30588236, 0.36862746, 0.43137255, 1.        ],
        [0.30980393, 0.37254903, 0.43529412, 1.        ],
        [0.3137255 , 0.3764706 , 0.4392157 , 1.        ],
        ...,
        [0.54509807, 0.5921569 , 0.65882355, 1.        ],
        [0.5568628 , 0.58431375, 0.6313726 , 1.        ],
        [0.5686275 , 0.5803922 , 0.6       , 1.        ]],

       [[0.28627452, 0.34901962, 0.40784314, 1.        ],
        [0.29411766, 0.35686275, 0.41568628, 1.        ],
        [0.29803923, 0.36078432, 0.41960785, 1.        ],
        ...,
        [0.54901963, 0.59607846, 0.6627451 , 1.        ],
        [0.5568628 , 0.5882353 , 0.6313726 , 1.        ],
        [0.57254905, 0.5803922 , 0.6039216 , 1.        ]],

       [[0.28235295, 0.34509805, 0.39607844, 1.        ],
        [0.28627452, 0.34901962, 0.40392157, 1.        ],
        [0.2901961 , 0.3529412 , 0.40392157, 1.        ],
        ...,
        [0.5568628 , 0.6       , 0.6627451 , 1.        ],
        [0.5686275 , 0.592156

In [123]:
img_arr.shape

(536, 680, 4)

In [125]:
img_arr.ndim

3

In [126]:
img_arr.size

1457920

In [127]:
img_arr[:5]

array([[[0.30588236, 0.36862746, 0.43137255, 1.        ],
        [0.30980393, 0.37254903, 0.43529412, 1.        ],
        [0.3137255 , 0.3764706 , 0.4392157 , 1.        ],
        ...,
        [0.54509807, 0.5921569 , 0.65882355, 1.        ],
        [0.5568628 , 0.58431375, 0.6313726 , 1.        ],
        [0.5686275 , 0.5803922 , 0.6       , 1.        ]],

       [[0.28627452, 0.34901962, 0.40784314, 1.        ],
        [0.29411766, 0.35686275, 0.41568628, 1.        ],
        [0.29803923, 0.36078432, 0.41960785, 1.        ],
        ...,
        [0.54901963, 0.59607846, 0.6627451 , 1.        ],
        [0.5568628 , 0.5882353 , 0.6313726 , 1.        ],
        [0.57254905, 0.5803922 , 0.6039216 , 1.        ]],

       [[0.28235295, 0.34509805, 0.39607844, 1.        ],
        [0.28627452, 0.34901962, 0.40392157, 1.        ],
        [0.2901961 , 0.3529412 , 0.40392157, 1.        ],
        ...,
        [0.5568628 , 0.6       , 0.6627451 , 1.        ],
        [0.5686275 , 0.592156